project:
  execute-dir: project
  type: website

execute:
  freeze: true

# bibliography:
#   - '../../../80-89 Resources/80 References/80.01 BibTex Bibliography/biology-research.bib'

format:
  html:
    theme:
      light:
        [
          theme/global-setting.scss,
          theme/style.scss,
          theme/custom-nav.scss,
          theme/callouts.scss,
          theme/sort-ui.scss,
        ]
      dark:
        [
          theme/global-setting.scss,
          theme/style-dark.scss,
          theme/custom-nav-dark.scss,
          theme/callouts-dark.scss,
          theme/sort-ui-dark.scss,
        ]
    toc: true
    toc-depth: 4
    toc-expand: 2
    code-copy: true
    code-overflow: wrap
    code-tools:
      caption: none
      source: true
    highlight-style: atom-one-dark

lightbox: true
